server:
  port: 8082

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  datasource:
    name: incomeadmin
    url: jdbc:mysql://127.0.0.1:3306/incomeadmin
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**


